name: "Install and build"

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up node.
        uses: actions/setup-node@v3.8.2
        with:
          node-version: 17.x
      - name: Install and build.
        run: |
          yarn install
          yarn build
        env:
          CI: true
      - name: Deploy!
        uses: demurgos/ga-deploy-git@v1
        if: ${{ github.event_name == 'push' }}
        with:
          accessToken: ${{ secrets.PUSH_TOKEN }}
          commitEmail: "bot@frozzare.com"
          commitUser: "Frozzbot"
          destBranch: "main"
          srcDir: "build"
